second
yunni0315/for-student pull request #1
Opened 2023-10-16 15:44 UTC by yunni0315

like this?

2023-10-16 16:06 UTC, bluejoyq requested changes

2023-10-16 16:06 UTC, bluejoyq commented on lib/main.dart
>          for (var pair in appState.favorites)
var을 사용할 이유가 없을텐데, 개발 도구가 잘 안 동작하는듯

2023-10-19 02:31 UTC, bluejoyq requested changes
대충 보이는것만 잡음~

2023-10-19 02:31 UTC, bluejoyq commented on lib/main.dart
> +import 'package:intl/intl.dart';
다국어로 서비스를 제공하기 위한 패키지인데 왜?!?!

2023-10-19 02:31 UTC, bluejoyq commented on lib/main.dart
> +//import 'package:english_words/english_words.dart';
이런건 주석처리보다 그냥 삭제하는걸 추천해. 어차피 커밋 기록이 남으니까.

2023-10-19 02:31 UTC, bluejoyq commented on lib/main.dart
> +  var favorites = <Future>[];
어떤 Future인지 타입을 정해주면 좋을 듯

2023-10-19 02:31 UTC, bluejoyq commented on lib/main.dart
> +        page = FavoritesPage();
page를 이런 식으로 나누고 싶은거면 go_router라는 패키지가 있음.

2023-10-19 02:31 UTC, bluejoyq commented on lib/main.dart
> +class Menu {
이 파일은 성격이 전혀 다른데 분리하는게 어떨까

2023-10-19 02:31 UTC, bluejoyq commented on lib/main.dart
> +Future<List<Menu>> getMealInfo({String schoolCode = '7530126'}) async {
얘도 마찬가지

2023-10-19 02:31 UTC, bluejoyq commented on lib/main.dart
> +      'https://open.neis.go.kr/hub/mealServiceDietInfo?Type=json&ATPT_OFCDC_SC_CODE=J10&SD_SCHUL_CODE=$schoolCode&MLSV_YMD=$dateStr'));
이런 상수값은 별도의 변수 ex) const API_END_POINT 같은걸로 빼자.
schoolCode도 마찬가지

2023-10-19 02:31 UTC, bluejoyq commented on lib/main.dart
> +  final response = await http.get(Uri.parse(
dio가 있는데 http를 사용한 이유는?

2023-10-19 15:54 UTC, merged

2023-10-19 15:56 UTC, yunni0315 commented on lib/main.dart
>          for (var pair in appState.favorites)
https://codelabs.developers.google.com/codelabs/flutter-codelab-first?hl=ko#0 여기 보고 따라한건데
오류가 있는 건가요?

2023-10-19 16:27 UTC, bluejoyq commented on lib/main.dart
>          for (var pair in appState.favorites)
내 취향이긴한데 pair는 불변이니까 const가 더 알맞을 것 같아